name: Build and Test Python API

# Déclencheurs : Push sur main et Pull Request
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout du code
      - name: Checkout code
        uses: actions/checkout@v4

      # Build manuel de l'image Docker (sans push)
      - name: Build Docker image
        run: |
          docker build -t python-api:test -f python.Dockerfile .

      # Lancement du conteneur en mode détaché
      - name: Launch container in detached mode
        run: |
          docker run -d --name test-api -p 8000:8000 python-api:test

      # Attendre que le conteneur soit prêt
      - name: Wait for container to be ready
        run: |
          echo "Waiting for container to start..."
          sleep 10

      # Lecture des logs sur un pattern distinguant
      - name: Check logs for startup pattern
        run: |
          echo "Checking container logs..."
          docker logs test-api
          # Vérifier la présence d'un pattern dans les logs (par exemple "Starting server" ou "Uvicorn running")
          docker logs test-api 2>&1 | grep -i "uvicorn\|running\|started\|server" || {
            echo "❌ Expected startup pattern not found in logs"
            exit 1
          }
          echo "✅ Startup pattern found in logs"

      # Smoke Test : Vérifier que le conteneur répond aux requêtes HTTP
      - name: Smoke Test - HTTP Health Check
        run: |
          echo "Performing smoke test..."
          # Vérifier que le conteneur est "Up"
          if [ "$(docker inspect -f '{{.State.Status}}' test-api)" != "running" ]; then
            echo "❌ Container is not running"
            exit 1
          fi
          echo "✅ Container is running"

          # Test de requête HTTP avec curl
          max_attempts=5
          attempt=1
          while [ $attempt -le $max_attempts ]; do
            echo "HTTP test attempt $attempt/$max_attempts"
            if curl -f -s http://localhost:8000/ > /dev/null; then
              echo "✅ HTTP request successful"
              break
            elif [ $attempt -eq $max_attempts ]; then
              echo "❌ HTTP request failed after $max_attempts attempts"
              docker logs test-api
              exit 1
            else
              echo "⏳ Waiting 5 seconds before retry..."
              sleep 5
              attempt=$((attempt + 1))
            fi
          done

          # Test additionnel : vérifier la réponse JSON
          echo "Testing API response..."
          response=$(curl -s http://localhost:8000/)
          echo "API Response: $response"

      # Nettoyage : Arrêt et suppression du conteneur
      - name: Cleanup
        if: always()
        run: |
          docker stop test-api || true
          docker rm test-api || true
          docker rmi python-api:test || true
